version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1810:1810"
    environment:
      APP_HOSTNAME: '0.0.0.0'
      APP_PORT: 1810
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    volumes:
      - storageimages:/public/cache/files
volumes:
  storageimages:
    external: true